export type CardRarity =
  | "Common"
  | "Uncommon"
  | "Rare"
  | "Epic"
  | "Legendary"
  | "Mythic"
  | "Divine";

export type AnimeCard = {
  id: string;
  name: string;
  anime: string;
  rarity: CardRarity;
  power: number;
  attack: number;
  defense: number;
  speed: number;
  ability: string;
  image_url: string;
};

export type JjkCard = AnimeCard;

export const JJK_CARDS: JjkCard[] = [
  {
    id: "jjk_gojo",
    name: "Satoru Gojo",
    anime: "Jujutsu Kaisen",
    rarity: "Mythic",
    power: 985,
    attack: 970,
    defense: 990,
    speed: 995,
    ability: "Infinity",
    image_url:
      "https://i.ibb.co/DDFDPjkQ/Satoru-Gojo-arrives-on-the-battlefield-Anime.webp",
  },
  {
    id: "jjk_yuji",
    name: "Yuji Itadori",
    anime: "Jujutsu Kaisen",
    rarity: "Epic",
    power: 870,
    attack: 900,
    defense: 860,
    speed: 850,
    ability: "Black Flash",
    image_url:
      "https://i.ibb.co/ycwQDffd/90ae68f0-22dc-43c1-939c-467a838d2b72-800x690.jpg",
  },
  {
    id: "jjk_yuki",
    name: "Yuki Tsukumo",
    anime: "Jujutsu Kaisen",
    rarity: "Legendary",
    power: 940,
    attack: 965,
    defense: 900,
    speed: 880,
    ability: "Star Rage",
    image_url: "https://i.ibb.co/1tCx031G/download-36.jpg",
  },
  {
    id: "jjk_sukuna",
    name: "Ryomen Sukuna",
    anime: "Jujutsu Kaisen",
    rarity: "Mythic",
    power: 1000,
    attack: 1000,
    defense: 975,
    speed: 965,
    ability: "Malevolent Shrine",
    image_url: "https://i.ibb.co/vvBmgdy2/images-5.webp",
  },
  {
    id: "jjk_todo",
    name: "Aoi Todo",
    anime: "Jujutsu Kaisen",
    rarity: "Epic",
    power: 825,
    attack: 880,
    defense: 850,
    speed: 820,
    ability: "Boogie Woogie",
    image_url: "https://i.ibb.co/FLrYFMZ1/images-69.jpg",
  },
  {
    id: "jjk_megumi",
    name: "Megumi Fushiguro",
    anime: "Jujutsu Kaisen",
    rarity: "Legendary",
    power: 900,
    attack: 875,
    defense: 860,
    speed: 850,
    ability: "Ten Shadows",
    image_url: "https://i.ibb.co/wZ3kJT9B/images-4.jpg",
  },
  {
    id: "jjk_yuta",
    name: "Yuta Okkotsu",
    anime: "Jujutsu Kaisen",
    rarity: "Mythic",
    power: 970,
    attack: 955,
    defense: 950,
    speed: 900,
    ability: "Copy",
    image_url: "https://i.ibb.co/Jwp5ddN2/images-3.webp",
  },
  {
    id: "jjk_kenjaku",
    name: "Kenjaku",
    anime: "Jujutsu Kaisen",
    rarity: "Legendary",
    power: 930,
    attack: 900,
    defense: 920,
    speed: 850,
    ability: "Cursed Technique Manipulation",
    image_url: "https://i.ibb.co/PsSDDbT4/download-37.jpg",
  },
  {
    id: "jjk_toji",
    name: "Toji Fushiguro",
    anime: "Jujutsu Kaisen",
    rarity: "Legendary",
    power: 925,
    attack: 965,
    defense: 850,
    speed: 975,
    ability: "Heavenly Restriction",
    image_url: "https://i.ibb.co/ZpmHWzK2/images-66.jpg",
  },
  {
    id: "jjk_maki",
    name: "Maki Zenin",
    anime: "Jujutsu Kaisen",
    rarity: "Legendary",
    power: 915,
    attack: 950,
    defense: 845,
    speed: 965,
    ability: "Heavenly Restriction",
    image_url: "https://i.ibb.co/KcnkrXhG/images-67.jpg",
  },
  {
    id: "jjk_mahito",
    name: "Mahito",
    anime: "Jujutsu Kaisen",
    rarity: "Legendary",
    power: 910,
    attack: 925,
    defense: 900,
    speed: 870,
    ability: "Idle Transfiguration",
    image_url: "https://i.ibb.co/zzMHn0M/images-68.jpg",
  },
];

export const BLEACH_CARDS: AnimeCard[] = [
  {
    id: "bleach_ichigo",
    name: "Ichigo Kurosaki",
    anime: "Bleach",
    rarity: "Mythic",
    power: 990,
    attack: 985,
    defense: 960,
    speed: 980,
    ability: "True Bankai",
    image_url: "https://i.ibb.co/Nn99sFPj/images-6.webp",
  },
  {
    id: "bleach_aizen",
    name: "Sosuke Aizen",
    anime: "Bleach",
    rarity: "Mythic",
    power: 995,
    attack: 970,
    defense: 990,
    speed: 950,
    ability: "Kyoka Suigetsu",
    image_url: "https://i.ibb.co/Mxs82rD0/7b1d07403241eb1f3b415fc75f93b1ea.jpg",
  },
  {
    id: "bleach_yhwach",
    name: "Yhwach",
    anime: "Bleach",
    rarity: "Divine",
    power: 1000,
    attack: 995,
    defense: 1000,
    speed: 970,
    ability: "The Almighty",
    image_url: "https://i.ibb.co/bxzKbSJ/images-7.webp",
  },
  {
    id: "bleach_byakuya",
    name: "Byakuya Kuchiki",
    anime: "Bleach",
    rarity: "Legendary",
    power: 930,
    attack: 925,
    defense: 915,
    speed: 940,
    ability: "Senbonzakura",
    image_url: "https://i.ibb.co/NdsPPsz2/images-8.webp",
  },
  {
    id: "bleach_yamamoto",
    name: "Genryusai Shigekuni Yamamoto",
    anime: "Bleach",
    rarity: "Mythic",
    power: 980,
    attack: 995,
    defense: 970,
    speed: 900,
    ability: "Zanka no Tachi",
    image_url: "https://i.ibb.co/Gv4cr8r7/images-9.webp",
  },
  {
    id: "bleach_orihime",
    name: "Orihime Inoue",
    anime: "Bleach",
    rarity: "Epic",
    power: 780,
    attack: 650,
    defense: 900,
    speed: 700,
    ability: "Soten Kisshun",
    image_url: "https://i.ibb.co/JFxW1zCf/images-10.webp",
  },
  {
    id: "bleach_rukia",
    name: "Rukia Kuchiki",
    anime: "Bleach",
    rarity: "Legendary",
    power: 900,
    attack: 900,
    defense: 880,
    speed: 910,
    ability: "Hakka no Togame",
    image_url:
      "https://i.ibb.co/601nGCvY/rukia-bankai-hakka-no-togame-bleach-thousand-year-blood-war-part-2-episode-6.jpg",
  },
  {
    id: "bleach_shunsui",
    name: "Shunsui Kyoraku",
    anime: "Bleach",
    rarity: "Mythic",
    power: 960,
    attack: 950,
    defense: 940,
    speed: 930,
    ability: "Katen Kyokotsu: Karamatsu Shinju",
    image_url: "https://i.ibb.co/vxtFzk5W/Ep401-Shunsui-Laments-Strength.webp",
  },
  {
    id: "bleach_kenpachi",
    name: "Kenpachi Zaraki",
    anime: "Bleach",
    rarity: "Mythic",
    power: 975,
    attack: 1000,
    defense: 950,
    speed: 900,
    ability: "Bankai",
    image_url: "https://i.ibb.co/ZprtytGB/Ep386-Kenpachi-Profile.webp",
  },
  {
    id: "bleach_ulquiorra",
    name: "Ulquiorra Cifer",
    anime: "Bleach",
    rarity: "Legendary",
    power: 925,
    attack: 940,
    defense: 920,
    speed: 950,
    ability: "Segunda Etapa",
    image_url: "https://i.ibb.co/k2pvsHSW/artworks-bi-TDJHbhl-MT9-TLg-V-gv3i-MA-t1080x1080.jpg",
  },
  {
    id: "bleach_jugram",
    name: "Jugram Haschwalth",
    anime: "Bleach",
    rarity: "Mythic",
    power: 950,
    attack: 930,
    defense: 960,
    speed: 900,
    ability: "The Balance",
    image_url: "https://i.ibb.co/yvPLnd4/images-70.jpg",
  },
  {
    id: "bleach_ichibei",
    name: "Ichibe Hyosube",
    anime: "Bleach",
    rarity: "Divine",
    power: 985,
    attack: 960,
    defense: 980,
    speed: 920,
    ability: "Ichimonji",
    image_url: "https://i.ibb.co/8g1Nk0H6/images-71.jpg",
  },
];

export const ALL_CARDS: AnimeCard[] = [...JJK_CARDS, ...BLEACH_CARDS];

// New anime sets can be added here without changing command or database code.
export const CARD_SETS: Record<string, AnimeCard[]> = {
  jjk: JJK_CARDS,
  bleach: BLEACH_CARDS,
};