export type CardRarity =
  | "Common"
  | "Uncommon"
  | "Rare"
  | "Epic"
  | "Legendary"
  | "Mythic"
  | "Divine"
  | "Celestial";

export type AnimeCard = {
  id: string;
  name: string;
  anime: string;
  rarity: CardRarity;
  power: number;
  attack: number;
  defense: number;
  speed: number;
  ability: string;
  image_url: string;
  banner?: string;
};

export type JjkCard = AnimeCard;

export const JJK_CARDS: JjkCard[] = [
  {
    id: "jjk_gojo",
    name: "Satoru Gojo",
    anime: "Jujutsu Kaisen",
    rarity: "Mythic",
    power: 985,
    attack: 970,
    defense: 990,
    speed: 995,
    ability: "Infinity",
    image_url:
      "https://i.ibb.co/DDFDPjkQ/Satoru-Gojo-arrives-on-the-battlefield-Anime.webp",
  },
  {
    id: "jjk_yuji",
    name: "Yuji Itadori",
    anime: "Jujutsu Kaisen",
    rarity: "Epic",
    power: 870,
    attack: 900,
    defense: 860,
    speed: 850,
    ability: "Black Flash",
    image_url:
      "https://i.ibb.co/ycwQDffd/90ae68f0-22dc-43c1-939c-467a838d2b72-800x690.jpg",
  },
  {
    id: "jjk_yuki",
    name: "Yuki Tsukumo",
    anime: "Jujutsu Kaisen",
    rarity: "Legendary",
    power: 940,
    attack: 965,
    defense: 900,
    speed: 880,
    ability: "Star Rage",
    image_url: "https://i.ibb.co/1tCx031G/download-36.jpg",
  },
  {
    id: "jjk_sukuna",
    name: "Ryomen Sukuna",
    anime: "Jujutsu Kaisen",
    rarity: "Mythic",
    power: 1000,
    attack: 1000,
    defense: 975,
    speed: 965,
    ability: "Malevolent Shrine",
    image_url: "https://i.ibb.co/vvBmgdy2/images-5.webp",
  },
  {
    id: "jjk_todo",
    name: "Aoi Todo",
    anime: "Jujutsu Kaisen",
    rarity: "Epic",
    power: 825,
    attack: 880,
    defense: 850,
    speed: 820,
    ability: "Boogie Woogie",
    image_url: "https://i.ibb.co/FLrYFMZ1/images-69.jpg",
  },
  {
    id: "jjk_megumi",
    name: "Megumi Fushiguro",
    anime: "Jujutsu Kaisen",
    rarity: "Legendary",
    power: 900,
    attack: 875,
    defense: 860,
    speed: 850,
    ability: "Ten Shadows",
    image_url: "https://i.ibb.co/wZ3kJT9B/images-4.jpg",
  },
  {
    id: "jjk_yuta",
    name: "Yuta Okkotsu",
    anime: "Jujutsu Kaisen",
    rarity: "Mythic",
    power: 970,
    attack: 955,
    defense: 950,
    speed: 900,
    ability: "Copy",
    image_url: "https://i.ibb.co/Jwp5ddN2/images-3.webp",
  },
  {
    id: "jjk_kenjaku",
    name: "Kenjaku",
    anime: "Jujutsu Kaisen",
    rarity: "Legendary",
    power: 930,
    attack: 900,
    defense: 920,
    speed: 850,
    ability: "Cursed Technique Manipulation",
    image_url: "https://i.ibb.co/PsSDDbT4/download-37.jpg",
  },
  {
    id: "jjk_toji",
    name: "Toji Fushiguro",
    anime: "Jujutsu Kaisen",
    rarity: "Legendary",
    power: 925,
    attack: 965,
    defense: 850,
    speed: 975,
    ability: "Heavenly Restriction",
    image_url: "https://i.ibb.co/ZpmHWzK2/images-66.jpg",
  },
  {
    id: "jjk_maki",
    name: "Maki Zenin",
    anime: "Jujutsu Kaisen",
    rarity: "Legendary",
    power: 915,
    attack: 950,
    defense: 845,
    speed: 965,
    ability: "Heavenly Restriction",
    image_url: "https://i.ibb.co/KcnkrXhG/images-67.jpg",
  },
  {
    id: "jjk_mahito",
    name: "Mahito",
    anime: "Jujutsu Kaisen",
    rarity: "Legendary",
    power: 910,
    attack: 925,
    defense: 900,
    speed: 870,
    ability: "Idle Transfiguration",
    image_url: "https://i.ibb.co/zzMHn0M/images-68.jpg",
  },
];

export const BLEACH_CARDS: AnimeCard[] = [
  {
    id: "bleach_ichigo",
    name: "Ichigo Kurosaki",
    anime: "Bleach",
    rarity: "Mythic",
    power: 990,
    attack: 985,
    defense: 960,
    speed: 980,
    ability: "True Bankai",
    image_url: "https://i.ibb.co/Nn99sFPj/images-6.webp",
  },
  {
    id: "bleach_aizen",
    name: "Sosuke Aizen",
    anime: "Bleach",
    rarity: "Mythic",
    power: 995,
    attack: 970,
    defense: 990,
    speed: 950,
    ability: "Kyoka Suigetsu",
    image_url: "https://i.ibb.co/Mxs82rD0/7b1d07403241eb1f3b415fc75f93b1ea.jpg",
  },
  {
    id: "bleach_yhwach",
    name: "Yhwach",
    anime: "Bleach",
    rarity: "Divine",
    power: 1000,
    attack: 995,
    defense: 1000,
    speed: 970,
    ability: "The Almighty",
    image_url: "https://i.ibb.co/bxzKbSJ/images-7.webp",
  },
  {
    id: "bleach_byakuya",
    name: "Byakuya Kuchiki",
    anime: "Bleach",
    rarity: "Legendary",
    power: 930,
    attack: 925,
    defense: 915,
    speed: 940,
    ability: "Senbonzakura",
    image_url: "https://i.ibb.co/NdsPPsz2/images-8.webp",
  },
  {
    id: "bleach_yamamoto",
    name: "Genryusai Shigekuni Yamamoto",
    anime: "Bleach",
    rarity: "Mythic",
    power: 980,
    attack: 995,
    defense: 970,
    speed: 900,
    ability: "Zanka no Tachi",
    image_url: "https://i.ibb.co/Gv4cr8r7/images-9.webp",
  },
  {
    id: "bleach_orihime",
    name: "Orihime Inoue",
    anime: "Bleach",
    rarity: "Epic",
    power: 780,
    attack: 650,
    defense: 900,
    speed: 700,
    ability: "Soten Kisshun",
    image_url: "https://i.ibb.co/JFxW1zCf/images-10.webp",
  },
  {
    id: "bleach_rukia",
    name: "Rukia Kuchiki",
    anime: "Bleach",
    rarity: "Legendary",
    power: 900,
    attack: 900,
    defense: 880,
    speed: 910,
    ability: "Hakka no Togame",
    image_url:
      "https://i.ibb.co/601nGCvY/rukia-bankai-hakka-no-togame-bleach-thousand-year-blood-war-part-2-episode-6.jpg",
  },
  {
    id: "bleach_shunsui",
    name: "Shunsui Kyoraku",
    anime: "Bleach",
    rarity: "Mythic",
    power: 960,
    attack: 950,
    defense: 940,
    speed: 930,
    ability: "Katen Kyokotsu: Karamatsu Shinju",
    image_url: "https://i.ibb.co/vxtFzk5W/Ep401-Shunsui-Laments-Strength.webp",
  },
  {
    id: "bleach_kenpachi",
    name: "Kenpachi Zaraki",
    anime: "Bleach",
    rarity: "Mythic",
    power: 975,
    attack: 1000,
    defense: 950,
    speed: 900,
    ability: "Bankai",
    image_url: "https://i.ibb.co/ZprtytGB/Ep386-Kenpachi-Profile.webp",
  },
  {
    id: "bleach_ulquiorra",
    name: "Ulquiorra Cifer",
    anime: "Bleach",
    rarity: "Legendary",
    power: 925,
    attack: 940,
    defense: 920,
    speed: 950,
    ability: "Segunda Etapa",
    image_url: "https://i.ibb.co/k2pvsHSW/artworks-bi-TDJHbhl-MT9-TLg-V-gv3i-MA-t1080x1080.jpg",
  },
  {
    id: "bleach_jugram",
    name: "Jugram Haschwalth",
    anime: "Bleach",
    rarity: "Mythic",
    power: 950,
    attack: 930,
    defense: 960,
    speed: 900,
    ability: "The Balance",
    image_url: "https://i.ibb.co/yvPLnd4/images-70.jpg",
  },
  {
    id: "bleach_ichibei",
    name: "Ichibe Hyosube",
    anime: "Bleach",
    rarity: "Divine",
    power: 985,
    attack: 960,
    defense: 980,
    speed: 920,
    ability: "Ichimonji",
    image_url: "https://i.ibb.co/8g1Nk0H6/images-71.jpg",
  },
];

export const CROSSOVER_CARDS: AnimeCard[] = [
  {
    id: "fate_saber_artoria",
    name: "Saber / Artoria",
    anime: "Fate/stay night",
    rarity: "Divine",
    power: 1900,
    attack: 1900,
    defense: 1900,
    speed: 1900,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/b5jv2Njb/images-11.webp",
    banner: "Crossover",
  },
  {
    id: "fate_archer_emiya",
    name: "Archer / EMIYA",
    anime: "Fate/stay night",
    rarity: "Mythic",
    power: 1750,
    attack: 1750,
    defense: 1750,
    speed: 1750,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/PG4bbpKv/images-74.jpg",
    banner: "Crossover",
  },
  {
    id: "fate_rin_tohsaka",
    name: "Rin Tohsaka",
    anime: "Fate/stay night",
    rarity: "Legendary",
    power: 1350,
    attack: 1350,
    defense: 1350,
    speed: 1350,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/JFyXm6Yc/images-75.jpg",
    banner: "Crossover",
  },
  {
    id: "fate_shirou_emiya",
    name: "Shirou Emiya",
    anime: "Fate/stay night",
    rarity: "Legendary",
    power: 1400,
    attack: 1400,
    defense: 1400,
    speed: 1400,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/vxVZF1T4/fate-series-fate-stay-night-shirou-emiya-wallpaper-preview.jpg",
    banner: "Crossover",
  },
  {
    id: "fate_sakura_matou",
    name: "Sakura Matou",
    anime: "Fate/stay night",
    rarity: "Mythic",
    power: 1650,
    attack: 1650,
    defense: 1650,
    speed: 1650,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/gZTW3hC2/Sakura-FGO.webp",
    banner: "Crossover",
  },
  {
    id: "fate_rider_medusa",
    name: "Rider / Medusa",
    anime: "Fate/stay night",
    rarity: "Mythic",
    power: 1600,
    attack: 1600,
    defense: 1600,
    speed: 1600,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/rRkV6vhd/Medusa-in-Heaven-s-Feel.webp",
    banner: "Crossover",
  },
  {
    id: "fate_illyasviel_einzbern",
    name: "Illyasviel von Einzbern",
    anime: "Fate/stay night",
    rarity: "Legendary",
    power: 1250,
    attack: 1250,
    defense: 1250,
    speed: 1250,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/hxHk7xWH/images-76.jpg",
    banner: "Crossover",
  },
  {
    id: "fate_berserker_heracles",
    name: "Berserker / Heracles",
    anime: "Fate/stay night",
    rarity: "Divine",
    power: 1850,
    attack: 1850,
    defense: 1850,
    speed: 1850,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/m5QdnmBw/Fsn-Berserker-anime.webp",
    banner: "Crossover",
  },
  {
    id: "fate_lancer_cu_chulainn",
    name: "Lancer / Cu Chulainn",
    anime: "Fate/stay night",
    rarity: "Mythic",
    power: 1700,
    attack: 1700,
    defense: 1700,
    speed: 1700,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/Pq2F0r3/images-77.jpg",
    banner: "Crossover",
  },
  {
    id: "fate_gilgamesh",
    name: "Gilgamesh",
    anime: "Fate/stay night",
    rarity: "Celestial",
    power: 2000,
    attack: 2000,
    defense: 2000,
    speed: 2000,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/8DyHLhNG/images-72.jpg",
    banner: "Crossover",
  },
  {
    id: "fate_kirei_kotomine",
    name: "Kirei Kotomine",
    anime: "Fate/stay night",
    rarity: "Legendary",
    power: 1300,
    attack: 1300,
    defense: 1300,
    speed: 1300,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/rR3nL8xj/kotomine-kirei-vs-jujutsu-kaisen-v0-4iej42k4fokd1.jpg",
    banner: "Crossover",
  },
  {
    id: "fate_assassin_sasaki_kojirou",
    name: "Assassin / Sasaki Kojirou",
    anime: "Fate/stay night",
    rarity: "Mythic",
    power: 1550,
    attack: 1550,
    defense: 1550,
    speed: 1550,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/mCb6mgzD/images-82.jpg",
    banner: "Crossover",
  },
  {
    id: "fate_caster_medea",
    name: "Caster / Medea",
    anime: "Fate/stay night",
    rarity: "Mythic",
    power: 1650,
    attack: 1650,
    defense: 1650,
    speed: 1650,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/BVhwPHBv/images-79.jpg",
    banner: "Crossover",
  },
  {
    id: "db_goku",
    name: "Goku",
    anime: "Dragon Ball",
    rarity: "Divine",
    power: 1900,
    attack: 1900,
    defense: 1900,
    speed: 1900,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/svhQL66R/81-XZLx-Q4-Ga-L-AC-UF894-1000-QL80.jpg",
    banner: "Crossover",
  },
  {
    id: "db_vegeta",
    name: "Vegeta",
    anime: "Dragon Ball",
    rarity: "Divine",
    power: 1850,
    attack: 1850,
    defense: 1850,
    speed: 1850,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/Xxtbf8Yr/images-87.jpg",
    banner: "Crossover",
  },
  {
    id: "db_gohan",
    name: "Gohan",
    anime: "Dragon Ball",
    rarity: "Divine",
    power: 1875,
    attack: 1875,
    defense: 1875,
    speed: 1875,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/s9sJvwjP/images-88.jpg",
    banner: "Crossover",
  },
  {
    id: "db_piccolo",
    name: "Piccolo",
    anime: "Dragon Ball",
    rarity: "Mythic",
    power: 1600,
    attack: 1600,
    defense: 1600,
    speed: 1600,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/BVCD6Vn7/images-89.jpg",
    banner: "Crossover",
  },
  {
    id: "db_trunks",
    name: "Trunks",
    anime: "Dragon Ball",
    rarity: "Mythic",
    power: 1650,
    attack: 1650,
    defense: 1650,
    speed: 1650,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/mChSjLPM/images-90.jpg",
    banner: "Crossover",
  },
  {
    id: "db_frieza",
    name: "Frieza",
    anime: "Dragon Ball",
    rarity: "Mythic",
    power: 1700,
    attack: 1700,
    defense: 1700,
    speed: 1700,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/XkyNKfVF/images-91.jpg",
    banner: "Crossover",
  },
  {
    id: "db_cell",
    name: "Cell",
    anime: "Dragon Ball",
    rarity: "Mythic",
    power: 1680,
    attack: 1680,
    defense: 1680,
    speed: 1680,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/Tq4svDpR/Cell-From-Dragon-Ball.jpg",
    banner: "Crossover",
  },
  {
    id: "db_majin_buu",
    name: "Majin Buu",
    anime: "Dragon Ball",
    rarity: "Divine",
    power: 1800,
    attack: 1800,
    defense: 1800,
    speed: 1800,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/HDvZS4NS/images-92.jpg",
    banner: "Crossover",
  },
  {
    id: "db_broly",
    name: "Broly",
    anime: "Dragon Ball",
    rarity: "Divine",
    power: 1950,
    attack: 1950,
    defense: 1950,
    speed: 1950,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/kVnWMBm6/images-93.jpg",
    banner: "Crossover",
  },
  {
    id: "db_beerus",
    name: "Beerus",
    anime: "Dragon Ball",
    rarity: "Celestial",
    power: 2000,
    attack: 2000,
    defense: 2000,
    speed: 2000,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/v4ZkBHfH/Beerus-Wikia-3.webp",
    banner: "Crossover",
  },
  {
    id: "db_whis",
    name: "Whis",
    anime: "Dragon Ball",
    rarity: "Celestial",
    power: 2000,
    attack: 2000,
    defense: 2000,
    speed: 2000,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/k26tCB9t/Whis-U7.webp",
    banner: "Crossover",
  },
  {
    id: "db_jiren",
    name: "Jiren",
    anime: "Dragon Ball",
    rarity: "Divine",
    power: 1900,
    attack: 1900,
    defense: 1900,
    speed: 1900,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/1fQscZLM/images-94.jpg",
    banner: "Crossover",
  },
  {
    id: "db_gogeta",
    name: "Gogeta",
    anime: "Dragon Ball",
    rarity: "Celestial",
    power: 2000,
    attack: 2000,
    defense: 2000,
    speed: 2000,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/C5HR9LLK/Gogeta-Base-Full.webp",
    banner: "Crossover",
  },
  {
    id: "rezero_subaru_natsuki",
    name: "Subaru Natsuki",
    anime: "Re:Zero",
    rarity: "Legendary",
    power: 1200,
    attack: 1200,
    defense: 1200,
    speed: 1200,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/mCQX61bN/images-12.webp",
    banner: "Crossover",
  },
  {
    id: "rezero_emilia",
    name: "Emilia",
    anime: "Re:Zero",
    rarity: "Mythic",
    power: 1650,
    attack: 1650,
    defense: 1650,
    speed: 1650,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/sp48d5nY/images-95.jpg",
    banner: "Crossover",
  },
  {
    id: "rezero_rem",
    name: "Rem",
    anime: "Re:Zero",
    rarity: "Mythic",
    power: 1500,
    attack: 1500,
    defense: 1500,
    speed: 1500,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/fsBtvQy/images-96.jpg",
    banner: "Crossover",
  },
  {
    id: "rezero_ram",
    name: "Ram",
    anime: "Re:Zero",
    rarity: "Mythic",
    power: 1550,
    attack: 1550,
    defense: 1550,
    speed: 1550,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/VYYybYJQ/images-97.jpg",
    banner: "Crossover",
  },
  {
    id: "rezero_beatrice",
    name: "Beatrice",
    anime: "Re:Zero",
    rarity: "Divine",
    power: 1750,
    attack: 1750,
    defense: 1750,
    speed: 1750,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/W4LFNfVq/images-98.jpg",
    banner: "Crossover",
  },
  {
    id: "rezero_reinhard_van_astrea",
    name: "Reinhard van Astrea",
    anime: "Re:Zero",
    rarity: "Celestial",
    power: 2000,
    attack: 2000,
    defense: 2000,
    speed: 2000,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/zV0hsnzp/images-99.jpg",
    banner: "Crossover",
  },
  {
    id: "rezero_echidna",
    name: "Echidna",
    anime: "Re:Zero",
    rarity: "Divine",
    power: 1750,
    attack: 1750,
    defense: 1750,
    speed: 1750,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/zTVwxv7g/images-100.jpg",
    banner: "Crossover",
  },
  {
    id: "rezero_roswaal_l_mathers",
    name: "Roswaal L. Mathers",
    anime: "Re:Zero",
    rarity: "Divine",
    power: 1800,
    attack: 1800,
    defense: 1800,
    speed: 1800,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/Qj90dPYp/Roswaal-L-Mathers-ep-12-4.webp",
    banner: "Crossover",
  },
  {
    id: "rezero_garfiel_tinzel",
    name: "Garfiel Tinzel",
    anime: "Re:Zero",
    rarity: "Mythic",
    power: 1550,
    attack: 1550,
    defense: 1550,
    speed: 1550,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/9R29DFq/images-2026-09-15-T185857-257.jpg",
    banner: "Crossover",
  },
  {
    id: "rezero_elsa_granhiert",
    name: "Elsa Granhiert",
    anime: "Re:Zero",
    rarity: "Legendary",
    power: 1400,
    attack: 1400,
    defense: 1400,
    speed: 1400,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/79P9tw4/Elsa-Granhirte-Anime.webp",
    banner: "Crossover",
  },
  {
    id: "rezero_satella_witch_of_envy",
    name: "Satella / Witch of Envy",
    anime: "Re:Zero",
    rarity: "Celestial",
    power: 2000,
    attack: 2000,
    defense: 2000,
    speed: 2000,
    ability: "Crossover Banner",
    image_url: "https://i.ibb.co/wZcqMj5am/217167364644981-1.webp",
    banner: "Crossover",
  },
];

export const CORE_CARDS: AnimeCard[] = [...JJK_CARDS, ...BLEACH_CARDS];

export const ALL_CARDS: AnimeCard[] = [...CORE_CARDS, ...CROSSOVER_CARDS];

// New anime sets can be added here without changing command or database code.
export const CARD_SETS: Record<string, AnimeCard[]> = {
  jjk: JJK_CARDS,
  bleach: BLEACH_CARDS,
  crossover: CROSSOVER_CARDS,
};